apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgfl_metadata.secret_name }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_USER: {{ .Values.pgfl_secret.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.pgfl_secret.postgres_password }}