apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fl_metadata.secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  FITROAD_LOCATIONS_DB_USERNAME: {{ .Values.fl_secret.db_user }}
  FITROAD_LOCATIONS_DB_PASSWORD: {{ .Values.fl_secret.db_password }}
