apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pgfl_metadata.pv_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pgfl_metadata.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pgfl_metadata.path }}