apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pgfl_metadata.pvc_name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pgfl_metadata.capacity }}